version: "2"
services:
  redis:
    container_name: redis
    image: redis:4

  smtp:
    build:
      dockerfile: smtp.docker
      context: ./smtp/
    container_name: smtp
    environment:
      SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}
      SMARTHOST_PORT=${SMARTHOST_PORT}
      SMARTHOST_USER=${SMARTHOST_USER}
      SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}

networks:
  default:
    external:
      name: nginx-proxy
