version: "2"
services:
  redis:
    container_name: redis
    image: redis:4

  smtp:
    image: namshi/smtp
    environment:
      SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}
      SMARTHOST_PORT=${SMARTHOST_PORT}
      SMARTHOST_USER=${SMARTHOST_USER}
      SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}
    volumes:
      - /etc/postfix/main.cf:/etc/postfix/main.cf
    ports:
      - 587:587

networks:
  default:
    external:
      name: nginx-proxy
